/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/advice-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 抽取有建议快照的练习样本供教师复核 */
        get: operations["AdminInsightsController_listAdviceSamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/advice-reviews/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 记录教师对结构建议的抽检结论与意见 */
        patch: operations["AdminInsightsController_reviewAdvice"];
        trace?: never;
    };
    "/api/v1/admin/analytics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按时间窗统计完整练习闭环关键漏斗 */
        get: operations["AdminInsightsController_funnel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/calligraphers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看书家主数据 */
        get: operations["ContentAdminController_listCalligraphers"];
        put?: never;
        /** 创建书家主数据并记录审计 */
        post: operations["ContentAdminController_createCalligrapher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/calligraphers/{calligrapherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ContentAdminController_updateCalligrapher"];
        trace?: never;
    };
    "/api/v1/admin/content/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listEditions"];
        put?: never;
        /** 创建作品版本并记录审计 */
        post: operations["ContentAdminController_createEdition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/editions/{editionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ContentAdminController_updateEdition"];
        trace?: never;
    };
    "/api/v1/admin/content/glyphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listGlyphs"];
        put?: never;
        /** 登记单字框并提交公开裁切任务 */
        post: operations["ContentAdminController_createGlyph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/glyphs/{glyphId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 纠正未发布单字并使既有审核失效 */
        patch: operations["ContentAdminController_updateGlyph"];
        trace?: never;
    };
    "/api/v1/admin/content/glyphs/{glyphId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在来源、权利、图片和审核均合格后发布单字 */
        post: operations["ContentAdminController_publishGlyph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/glyphs/{glyphId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以独立审核角色复核单字 */
        post: operations["ContentAdminController_reviewGlyph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/glyphs/{glyphId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 立即下架已发布单字并记录原因 */
        post: operations["ContentAdminController_unpublishGlyph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listContentHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/history/{auditId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_restoreContentHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/import-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listContentImportBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/import-batches/{batchId}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_commitContentImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/import-batches/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_previewContentImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_contentImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/rights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listRights"];
        put?: never;
        /** 创建权利记录并记录审计 */
        post: operations["ContentAdminController_createRights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/rights/{rightsId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ContentAdminController_updateRights"];
        trace?: never;
    };
    "/api/v1/admin/content/segmentation-candidates/{candidateId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_acceptSegmentationCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/segmentation-candidates/{candidateId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_rejectSegmentationCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/segmentation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listSegmentationJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/source-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_listSourceAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/source-assets/{sourceAssetId}/segmentation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentAdminController_createSegmentationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/source-assets/{sourceAssetId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentAdminController_createSourceAssetView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/source-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建带大小、格式和校验值约束的原帖直传 */
        post: operations["ContentAdminController_createSourceUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/source-uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 核验原帖直传并创建不可变来源资产 */
        post: operations["ContentAdminController_completeSourceUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看作品主数据 */
        get: operations["ContentAdminController_listWorks"];
        put?: never;
        /** 创建碑帖作品并记录审计 */
        post: operations["ContentAdminController_createWork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/works/{workId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ContentAdminController_updateWork"];
        trace?: never;
    };
    "/api/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按类型和状态查看用户反馈工单 */
        get: operations["AdminFeedbackController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feedback/{feedbackId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 分派、更新或关闭反馈工单 */
        patch: operations["AdminFeedbackController_update"];
        trace?: never;
    };
    "/api/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录内容管理后台 */
        post: operations["AdminSessionController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artwork-deletions/{deletionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PracticeController_getArtworkDeletion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artworks/{artworkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本人作品及图片质检状态 */
        get: operations["AnalysisController_getArtwork"];
        put?: never;
        post?: never;
        delete: operations["PracticeController_deleteArtwork"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artworks/{artworkId}/character": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认本人作品中的汉字 */
        post: operations["AnalysisController_confirmCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character}/glyphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询一个汉字已发布且授权公开的名家范字 */
        get: operations["CatalogController_findGlyphs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 幂等记录不含自由文本的核心业务事件 */
        post: operations["InsightsController_track"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorite-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PracticeController_createFavoriteGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorite-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PracticeController_removeFavoriteGroup"];
        options?: never;
        head?: never;
        patch: operations["PracticeController_updateFavoriteGroup"];
        trace?: never;
    };
    "/api/v1/favorite-groups/{groupId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PracticeController_reorderFavoriteGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PracticeController_listFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/glyphs/{glyphId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["PracticeController_favorite"];
        post?: never;
        delete: operations["PracticeController_unfavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/glyphs/{glyphId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PracticeController_reorderFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看当前用户反馈的处理进度 */
        get: operations["FeedbackController_list"];
        put?: never;
        /** 提交结构提示、质检、内容或产品反馈 */
        post: operations["FeedbackController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/glyphs/{glyphId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取已发布范字的来源上下文，不暴露私有原帖对象 */
        get: operations["GlyphController_getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立匿名学习会话 */
        post: operations["IdentityController_createAnonymousSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 一次性轮换 Refresh Token 并签发新访问令牌 */
        post: operations["IdentityController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销一个 Refresh Token；结果不暴露令牌是否存在 */
        post: operations["IdentityController_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为仍有效的旧版访问令牌建立可轮换会话 */
        post: operations["IdentityController_createRefreshableSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PracticeController_listPractices"];
        put?: never;
        /** 以本人作品和已发布同字范字创建练习记录 */
        post: operations["PracticeController_createPractice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PracticeController_getPractice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{sessionId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PracticeController_addAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{sessionId}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PracticeController_createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前用户相互独立的存储、公开和训练授权 */
        get: operations["PrivacyController_get"];
        /** 更新隐私授权并写入不可变授权审计记录 */
        put: operations["PrivacyController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PracticeController_revokeShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看未撤销且未过期的公开练习分享 */
        get: operations["PublicShareController_getShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看不含用户图片地址的公开练习分享摘要 */
        get: operations["PublicShareController_getShareSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建用户作品直传会话 */
        post: operations["UploadController_createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{uploadId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消尚未完成的直传并清理私有对象 */
        post: operations["UploadController_cancelUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认对象存储上传完成 */
        post: operations["UploadController_completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArtworkAnalysis: {
            findings: components["schemas"]["QualityFinding"][];
            metrics: components["schemas"]["QualityMetrics"] | null;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "PASSED" | "NEEDS_RETAKE" | "FAILED";
            thresholdVersion: string | null;
        };
        ArtworkAnalysisView: {
            analysis: components["schemas"]["ArtworkAnalysis"] | null;
            /** Format: uuid */
            artworkId: string;
            /** @enum {string} */
            artworkStatus: "PENDING_UPLOAD" | "UPLOADED" | "PROCESSING" | "READY" | "FAILED" | "DELETION_PENDING" | "DELETED";
            confirmedCharacter: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ArtworkDeletionView: {
            /** Format: uuid */
            artworkId: string;
            /** Format: uuid */
            deletionId: string;
            /** @enum {string} */
            status: "DELETION_PENDING" | "DELETED" | "FAILED";
            /** Format: date-time */
            updatedAt: string;
        };
        CalligrapherSummary: {
            dynasty: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
        CancelUploadResult: {
            /** Format: uuid */
            artworkId: string;
            /** @enum {string} */
            status: "DELETED";
            /** Format: uuid */
            uploadId: string;
        };
        CatalogFacets: {
            calligraphers: components["schemas"]["CalligrapherSummary"][];
            scriptStyles: "REGULAR"[];
            works: components["schemas"]["WorkSummary"][];
        };
        CatalogFilters: {
            /** Format: uuid */
            calligrapherId?: string;
            /** @enum {string} */
            scriptStyle?: "REGULAR";
            /** Format: uuid */
            workId?: string;
        };
        CatalogGlyphResult: {
            canonicalCharacter: string | null;
            facets: components["schemas"]["CatalogFacets"];
            filters: components["schemas"]["CatalogFilters"];
            glyphs: components["schemas"]["PublishedGlyph"][];
            query: string;
        };
        CharacterConfirmationRequest: {
            character: string;
        };
        CharacterConfirmationResult: {
            character: string;
        };
        CompleteUploadResult: {
            /** Format: uuid */
            analysisId: string;
            /** Format: uuid */
            artworkId: string;
            /** @enum {string} */
            status: "PROCESSING";
            /** Format: date-time */
            uploadedAt: string;
        };
        CreateFavoriteGroupRequest: {
            name: string;
        };
        CreatePracticeRequest: {
            /** Format: uuid */
            artworkId: string;
            /** Format: uuid */
            glyphId: string;
        };
        CreateUploadRequest: {
            clientRequestId: string;
            height: number;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            width: number;
        };
        CreateUploadResult: {
            /** Format: uuid */
            artworkId: string;
            /** Format: date-time */
            expiresAt: string;
            requiredHeaders: {
                /** @enum {string} */
                "content-type": "image/jpeg" | "image/png" | "image/webp";
            };
            /** Format: uuid */
            uploadId: string;
            /** Format: uri */
            uploadUrl: string;
        };
        DeleteFavoriteGroupResult: {
            deleted: boolean;
            /** Format: uuid */
            id: string;
        };
        FavoriteGlyphItem: {
            character: string;
            /** Format: uuid */
            favoriteId: string;
            glyph: components["schemas"]["PublishedGlyph"];
            /** Format: uuid */
            groupId: string | null;
            sortOrder: number;
        };
        FavoriteGroup: {
            /** Format: uuid */
            id: string;
            items: components["schemas"]["FavoriteGlyphItem"][];
            name: string;
            sortOrder: number;
        };
        FavoriteGroupResult: {
            /** Format: uuid */
            id: string;
            name: string;
            sortOrder: number;
        };
        FavoriteLibrary: {
            groups: components["schemas"]["FavoriteGroup"][];
            ungrouped: components["schemas"]["FavoriteGlyphItem"][];
        };
        FavoritePlacementRequest: {
            /** Format: uuid */
            groupId?: string | null;
        };
        FavoriteStateResult: {
            favorite: boolean;
            /** Format: uuid */
            glyphId: string;
        };
        FeedbackCreatedResult: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "DISMISSED";
        };
        FeedbackSubmitRequest: {
            accurate?: boolean;
            /** @enum {string} */
            kind: "STRUCTURE_ADVICE" | "RECOGNITION_ERROR" | "QUALITY_RESULT" | "CONTENT_ERROR" | "PRODUCT";
            message?: string;
            /** Format: uuid */
            referenceId?: string;
            /** @enum {string} */
            referenceType?: "Artwork" | "Glyph" | "PracticeSession";
        };
        GlyphDetail: components["schemas"]["PublishedGlyph"] & {
            character: string;
            /** Format: date-time */
            publishedAt: string;
            sourceContext: components["schemas"]["SourceContext"];
        };
        GlyphImage: {
            height: number;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "GLYPH_CROP" | "THUMBNAIL";
            /** Format: uri */
            url: string;
            width: number;
        };
        HealthResult: {
            /** @enum {string} */
            service: "api";
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        IdentitySession: {
            accessToken: string;
            expiresInSeconds: number;
            refreshExpiresInSeconds: number;
            refreshToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            user: components["schemas"]["SessionUser"];
        };
        PracticeAdvice: {
            /** @enum {string} */
            advanced_analysis_status: "UNAVAILABLE_NO_VALIDATED_CHARACTER_RULE";
            master: components["schemas"]["StructureMetrics"];
            /** @enum {string} */
            measurement_version: "structure-measurement-v2";
            /** @enum {string} */
            model_version: "no-ml-geometry-v1";
            /** @enum {string} */
            normalization_version: "glyph-normalization-v1";
            /** @enum {string} */
            status: "OK" | "LOW_CONFIDENCE";
            suggestions: components["schemas"]["StructureSuggestion"][];
            /** @enum {string} */
            threshold_version: "structure-v1";
            user: components["schemas"]["StructureMetrics"];
        } & {
            [key: string]: unknown;
        };
        PracticeAnalysisState: {
            failureCode: string | null;
            /** @enum {string} */
            status: "PENDING" | "READY" | "FAILED";
        };
        PracticeAttempt: {
            advice: components["schemas"]["PracticeAdvice"] | null;
            analysis: components["schemas"]["PracticeAnalysisState"] | null;
            /** Format: uuid */
            artworkId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uri */
            imageUrl: string;
            sequence: number;
        };
        PracticeAttemptRequest: {
            /** Format: uuid */
            artworkId: string;
        };
        PracticeMaster: {
            calligrapherName: string;
            /** Format: uuid */
            glyphId: string;
            /** Format: uri */
            imageUrl: string | null;
            workTitle: string;
        };
        PracticeView: {
            attempts: components["schemas"]["PracticeAttempt"][];
            character: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            master: components["schemas"]["PracticeMaster"];
        };
        PrivacyPreferences: {
            allowArtworkStorage: boolean;
            allowModelTraining: boolean;
            allowPublicSharing: boolean;
            policyVersion: string;
            /** Format: date-time */
            sharingUpdatedAt: string;
            /** Format: date-time */
            storageUpdatedAt: string;
            /** Format: date-time */
            trainingUpdatedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PrivacyPreferencesUpdate: {
            allowArtworkStorage?: boolean;
            allowModelTraining?: boolean;
            allowPublicSharing?: boolean;
        };
        ProductEventRequest: {
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            name: "ARTWORK_UPLOAD_COMPLETED" | "CHARACTER_CONFIRMED" | "CATALOG_RESULTS_VIEWED" | "GLYPH_SELECTED" | "PRACTICE_CREATED" | "ADVICE_VIEWED" | "SECOND_ATTEMPT_STARTED" | "PRACTICE_COMPLETED";
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            practiceSessionId?: string | null;
        };
        ProductEventResult: {
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            status: "RECORDED" | "DUPLICATE";
        };
        PublishedEdition: {
            holdingInstitution: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uri */
            sourceUrl: string | null;
        };
        PublishedGlyph: {
            /** @enum {string} */
            authenticityGrade: "A_ORIGINAL" | "B_RUBBING_OR_AUTHORIZED_EDITION" | "C_MODERN_COPY";
            beginnerWeight: number;
            calligrapher: components["schemas"]["CalligrapherSummary"];
            edition: components["schemas"]["PublishedEdition"];
            /** Format: uuid */
            id: string;
            image: components["schemas"]["GlyphImage"] | null;
            imageQuality: number;
            rights: components["schemas"]["PublishedRights"];
            /** @enum {string} */
            scriptStyle: "REGULAR";
            work: components["schemas"]["PublishedWork"];
        };
        PublishedRights: {
            attributionText: string | null;
            licenseName: string | null;
            sourceName: string;
            /** Format: uri */
            sourceUrl: string | null;
        };
        PublishedWork: {
            /** Format: uuid */
            id: string;
            title: string;
        };
        QualityFinding: {
            /** @enum {string} */
            code: "BLURRY" | "INK_TOUCHES_BORDER" | "LOW_CONTRAST" | "RESOLUTION_TOO_LOW" | "TOO_BRIGHT" | "TOO_DARK";
            message: string;
            /** @enum {string} */
            severity: "warning" | "error";
        };
        QualityMetrics: {
            blur_score: number;
            brightness: number;
            contrast: number;
            edge_ink_ratio: number;
            height: number;
            ink_coverage: number;
            width: number;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        ReorderRequest: {
            /** @enum {string} */
            direction: "UP" | "DOWN";
        };
        ReorderResult: {
            /** Format: uuid */
            glyphId?: string;
            /** Format: uuid */
            groupId?: string;
            reordered: boolean;
        };
        RevokeSessionResult: {
            revoked: boolean;
        };
        RevokeShareResult: {
            revoked: boolean;
            /** Format: uuid */
            shareId: string;
        };
        SessionUser: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "anonymous" | "registered";
        };
        ShareResult: {
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
        };
        ShareSummary: {
            attemptCount: number;
            character: string;
            master: {
                calligrapherName: string;
                workTitle: string;
            };
        };
        SourceContext: {
            boundingBox: components["schemas"]["SourceRectangle"];
            pageLabel: string | null;
            sourceImage: components["schemas"]["SourceImageSize"];
        };
        SourceImageSize: {
            height: number;
            width: number;
        };
        SourceRectangle: {
            height: number;
            width: number;
            x: number;
            y: number;
        };
        StructureMetrics: {
            anomalies: ("NO_FOREGROUND" | "TOO_SPARSE" | "TOO_DENSE" | "TOUCHES_EDGE" | "FRAGMENTED_FOREGROUND")[];
            bbox_height_ratio: number;
            bbox_left_ratio: number;
            bbox_top_ratio: number;
            bbox_width_ratio: number;
            centroid_x: number;
            centroid_y: number;
            confidence: number;
            foreground_ratio: number;
            ink_aspect_ratio: number;
            normalization: {
                /** @enum {integer} */
                canvas_height: 512;
                /** @enum {integer} */
                canvas_width: 512;
                offset_x: number;
                offset_y: number;
                scale: number;
                source_height: number;
                source_width: number;
                /** @enum {string} */
                version: "glyph-normalization-v1";
            };
            spatial_distribution: {
                bottom_left: number;
                bottom_right: number;
                top_left: number;
                top_right: number;
            };
        };
        StructureSuggestion: {
            action: string;
            /** @enum {string} */
            code: "CENTER_X" | "CENTER_Y" | "PROPORTION";
            evidence: string;
            phenomenon: string;
        };
        UpdateFavoriteGroupRequest: {
            name: string;
        };
        UpdateFavoriteGroupResult: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        UserFeedbackTicket: {
            accurate: boolean | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "STRUCTURE_ADVICE" | "RECOGNITION_ERROR" | "QUALITY_RESULT" | "CONTENT_ERROR" | "PRODUCT";
            message: string | null;
            /** Format: uuid */
            referenceId: string | null;
            referenceType: string | null;
            resolutionNote: string | null;
            /** Format: date-time */
            resolvedAt: string | null;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "DISMISSED";
            /** Format: date-time */
            updatedAt: string;
        };
        WorkSummary: {
            /** Format: uuid */
            calligrapherId: string;
            /** Format: uuid */
            id: string;
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminInsightsController_listAdviceSamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminInsightsController_reviewAdvice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminInsightsController_funnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listCalligraphers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createCalligrapher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_updateCalligrapher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listEditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createEdition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_updateEdition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listGlyphs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createGlyph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_updateGlyph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_publishGlyph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_reviewGlyph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_unpublishGlyph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listContentHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_restoreContentHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listContentImportBatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_commitContentImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_previewContentImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_contentImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listRights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createRights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_updateRights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_acceptSegmentationCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_rejectSegmentationCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listSegmentationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listSourceAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createSegmentationJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createSourceAssetView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createSourceUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_completeSourceUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_listWorks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_createWork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContentAdminController_updateWork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminFeedbackController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminFeedbackController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSessionController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PracticeController_getArtworkDeletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deletionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作品物理清理状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkDeletionView"];
                };
            };
        };
    };
    AnalysisController_getArtwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作品质检状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkAnalysisView"];
                };
            };
        };
    };
    PracticeController_deleteArtwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作品逻辑删除及物理清理状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkDeletionView"];
                };
            };
        };
    };
    AnalysisController_confirmCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artworkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterConfirmationRequest"];
            };
        };
        responses: {
            /** @description 汉字已确认。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterConfirmationResult"];
                };
            };
        };
    };
    CatalogController_findGlyphs: {
        parameters: {
            query?: {
                calligrapherId?: string;
                scriptStyle?: "REGULAR";
                workId?: string;
            };
            header?: never;
            path: {
                character: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已审核的公开范字结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogGlyphResult"];
                };
            };
        };
    };
    InsightsController_track: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductEventRequest"];
            };
        };
        responses: {
            /** @description 业务事件已记录。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductEventResult"];
                };
            };
        };
    };
    PracticeController_createFavoriteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFavoriteGroupRequest"];
            };
        };
        responses: {
            /** @description 收藏分组已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteGroupResult"];
                };
            };
        };
    };
    PracticeController_removeFavoriteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收藏分组已删除。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFavoriteGroupResult"];
                };
            };
        };
    };
    PracticeController_updateFavoriteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFavoriteGroupRequest"];
            };
        };
        responses: {
            /** @description 收藏分组已更新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateFavoriteGroupResult"];
                };
            };
        };
    };
    PracticeController_reorderFavoriteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description 收藏分组已重新排序。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReorderResult"];
                };
            };
        };
    };
    PracticeController_listFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户的收藏字帖。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteLibrary"];
                };
            };
        };
    };
    PracticeController_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glyphId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FavoritePlacementRequest"];
            };
        };
        responses: {
            /** @description 范字已收藏。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteStateResult"];
                };
            };
        };
    };
    PracticeController_unfavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glyphId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 范字收藏已取消。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteStateResult"];
                };
            };
        };
    };
    PracticeController_reorderFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glyphId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description 收藏范字已重新排序。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReorderResult"];
                };
            };
        };
    };
    FeedbackController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户的反馈工单。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFeedbackTicket"][];
                };
            };
        };
    };
    FeedbackController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmitRequest"];
            };
        };
        responses: {
            /** @description 反馈工单已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCreatedResult"];
                };
            };
        };
    };
    GlyphController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                glyphId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公开范字来源详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlyphDetail"];
                };
            };
        };
    };
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResult"];
                };
            };
        };
    };
    IdentityController_createAnonymousSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话已签发。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySession"];
                };
            };
        };
    };
    IdentityController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 会话已签发。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySession"];
                };
            };
        };
    };
    IdentityController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 撤销请求已处理。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResult"];
                };
            };
        };
    };
    IdentityController_createRefreshableSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话已签发。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySession"];
                };
            };
        };
    };
    PracticeController_listPractices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户的练习历史。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"][];
                };
            };
        };
    };
    PracticeController_createPractice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeRequest"];
            };
        };
        responses: {
            /** @description 练习会话已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"];
                };
            };
        };
    };
    PracticeController_getPractice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 练习会话详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"];
                };
            };
        };
    };
    PracticeController_addAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeAttemptRequest"];
            };
        };
        responses: {
            /** @description 再次练习已加入会话。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"];
                };
            };
        };
    };
    PracticeController_createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 私密练习分享已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResult"];
                };
            };
        };
    };
    PrivacyController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前隐私偏好。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyPreferences"];
                };
            };
        };
    };
    PrivacyController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivacyPreferencesUpdate"];
            };
        };
        responses: {
            /** @description 隐私偏好已更新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyPreferences"];
                };
            };
        };
    };
    PracticeController_revokeShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分享已撤销。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeShareResult"];
                };
            };
        };
    };
    PublicShareController_getShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公开练习分享。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"];
                };
            };
        };
    };
    PublicShareController_getShareSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 不包含用户图片地址的公开分享摘要。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareSummary"];
                };
            };
        };
    };
    UploadController_createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description 上传会话已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadResult"];
                };
            };
        };
    };
    UploadController_cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传已取消并清理。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelUploadResult"];
                };
            };
        };
    };
    UploadController_completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传已校验并进入质检。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUploadResult"];
                };
            };
        };
    };
}
