ALTER TYPE "ContentAuditAction" ADD VALUE 'UPDATE_FEEDBACK';
ALTER TYPE "FeedbackKind" ADD VALUE 'RECOGNITION_ERROR';
ALTER TYPE "FeedbackStatus" ADD VALUE 'IN_PROGRESS';
ALTER TYPE "FeedbackStatus" ADD VALUE 'DISMISSED';

ALTER TABLE "user_feedback"
  ADD COLUMN "assigned_to" VARCHAR(100),
  ADD COLUMN "resolution_note" TEXT,
  ADD COLUMN "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
